# Generated by Django 4.1.7 on 2023-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieflix", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="Email",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
