# Generated by Django 2.1.5 on 2023-02-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
