# Generated by Django 4.1.7 on 2023-03-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movieflix", "0002_alter_userprofile_email"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="Email",),
    ]
