# Generated by Django 3.2.18 on 2023-03-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0002_auto_20230311_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Average_Rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
