# Generated by Django 3.2.18 on 2023-03-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0003_movie_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='IMDB_Rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
