# Generated by Django 4.1.7 on 2023-03-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movieflix", "0003_remove_userprofile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="Email",
            field=models.EmailField(default=0, max_length=254, unique=True),
        ),
    ]
