# Generated by Django 3.2.18 on 2023-03-18 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0004_alter_movie_imdb_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='First_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_staff',
            new_name='Is_Staff',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Last_name',
            new_name='Last_Name',
        ),
    ]
