# Generated by Django 3.2.18 on 2023-03-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieflix', '0005_auto_20230318_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='First_Name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Password',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
